config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :locations, only: [:index, :show, :new] do
    resources :bikes do
       resources :bookings
       resources :reviews, only: [:new, :create]
    end
  end

  resources :users, only: [:show] do
    resource :profile, only: [:show, :edit, :update]
  end

  get "search", to: "pages#search"
  root "pages#welcome"

end

app/views/shared/_booking.html.erb
<div class="text-center">
  <h3>Book This Bike!</h3>
  <div class="form-box">

  <%= simple_form_for [@location, @bike, @booking], html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.button :submit, class: "btn btn-treehouse" %>
  <% end %>


  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-dark" id="footer">
  <footer class="container">
    <div class="row">
      <div class="col-md-6 col-sm-offset-1 col-md-offset-3">
        <div class="lang-curr-picker" id="lang-curr-picker">
          <div class="language-picker">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Language
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">English</a></li>
                <li><a href="#">French</a></li>
              </ul>
            </div>
          </div>
          <div class="currency-picker">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Currency
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <li><a href="#">Euro</a></li>
                <li><a href="#">Dollar</a></li>
                <li><a href="#">Pound</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12">
      <ul class="list-inline text-center padded-top-bottom">
        <li><a href="#">About</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Press</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Terms & Privacy</a></li>
      </ul>
    </div>
    <div class="text-center">
      <ul class="list-inline space-top">
        <li><a href="#" class="footer-icon-container"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-pinterest-p"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-youtube-play"></i></a></li>
        <li><a href="#" class="footer-icon-container"><i class="fa fa-instagram"></i></a></li>
      </ul>
      <div class="text-muted space-top">
        © Airbnb, Inc.
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "vespa.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
     <div class="navbar-wagon-item">
       <div class="dropdown">
         <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-users-people/57/thin-191_user_profile_avatar-512.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">


           <li>
             <%= link_to user_profile_path(current_user) do %>
               <i class="fa fa-user"></i>  <%= t ".profile", default: "Profile" %>
             <% end %>
           </li>
           <li>
             <%= link_to destroy_user_session_path, method: :delete do %>
               <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
             <% end %>
           </li>

         </ul>
       </div>
     </div>
      <!-- Profile picture and dropdown -->


    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>