config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :locations, only: [:index, :show, :new] do
    resources :bikes do
       resources :bookings
       resources :reviews, only: [:new, :create]
    end
  end

  resources :users, only: [:show] do
    resource :profile, only: [:show, :edit, :update]
  end

  get "search", to: "pages#search"
  root "pages#welcome"

end

app/views/pages/search.html.erb
<div class="wrapper text-center">
  <h2>Bikes Available in <%= @location.city%></h2>
  <div class="container container-local">
    <div class="row">
      <% @bikes.each do |bike| %>
      <div class="col-sm-6 col-md-4">

        <%= link_to location_bike_path(bike.location, bike) do %>
        <div class="card" style="background-image: url('<%= image_url bike.bike_image %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

          <div class="card-category"><%= bike.make %></div>
          <div class="card-description">
            <h2><%= bike.model %></h2>
          </div>

        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="banner text-center" style="background-image: linear-gradient(23deg, rgba(0,0,0,0) -158%, rgba(0,4,13,9) 143%), url('http://www.weareninetynine.co/wp-content/uploads/2015/09/DGr_Sydney206280915.jpg');">
  <div class="banner-content">
    <h1>RIDE ON</h1>
    <p>PICK A RIDE, GO ANYWHERE</p>
     <div class="wrapper-form">


      <%= form_tag search_path(Booking.new),method: :get, class:"form-inline text-center form"  do %>
        <%= select_tag :location_id, options_from_collection_for_select(@locations, :id, :city ), class:"form-control input-md" %>
        <%= date_field_tag 'start_date', nil, class:"form-control input-md"%>
        <%= date_field_tag 'end_date', nil, class:"form-control input-md" %>
        <%= submit_tag "Search", class:"btn btn-primary btn-md" %>
      <% end %>



       <!--  <input type="date" class="form-control input-md" placeholder="check in">
        <input type="date" class="form-control input-md" placeholder="check out">
        <select class="form-control input-md" placeholder="Type">
          <option value="1">Type</option>
          <option value="2">Scooter</option>
          <option value="3">Motorcycle</option>
          <option value="4">Moped</option>
        </select> -->
        <!-- <input type="submit" class="btn btn-info btn-md" value="Search"> -->


      <br><br>

    </div>
  </div>
</div>

<div class="banner-wrapper">
  <div class="banner-content-center text-center">

    <h1>MAKE REVENUE WITH YOUR BIKE</h1>
    <p>List your bike for free and rent to whenever you want.
    Bikes get lonely too.
    </p>
    <br>

    <div class="text-center">
    <a href="#" class="btn btn-primary btn-lg" role="button">How it works</a>
    </div>

  </div>

</div>



<div class="container-local text-center">

<!--   <div class="card-title">
  <h2>DESTINATIONS</h2> -->
<!--   </div> -->

  <div class="row">
    <% @locations.each do |location| %>
    <div class="card-padding col-sm-6 col-md-4 highlight">

      <%= link_to location_path(location) do %>
      <div class="card" style="background-image: url('<%= image_url location.image %>');">
      <div class="overlay"></div>

        <div class="info"></div>
        <div class="card-description">
          <h2><%= location.city %></h2>
        </div>

      </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <script>
  $(".card").hover(
    function(){
        $(".info", this).css("display", "block");
    }, function(){
        $(".info", this).css("display", "none");
  });
  </script>


</div>

<!-- <div id="how-to">
  <div class="banner-a" style="background-image: linear-gradient(23deg, rgba(0,0,0,0) -158%, rgba(0,4,13,9) 143%), url('http://www.motowallpapers.com/custom/i/icon/2012-the-roach-1986-harley-davidson-sportster/Icon-The-Roach-2012-Harley-Davidson-Sportster-1986-1920x1080-003.jpg');">



    <div class="banner-contents text-center ">
      <h1>How it works</h1>
      <div class="row">
        <div class="col-md-4">
          <h1><i class="fa fa-plane"></i></h1>
          <h2>Decide</h2>
          <p>Where you wanna ride around</p>
        </div>
        <div class="col-md-4">
          <h1><i class="fa fa-calendar"></i></h1>
          <h2>Choose</h2>
          <p>The bike of your dreams</p>
        </div>
        <div class="col-md-4">
          <h1><i class="fa fa-group"></i></h1>
          <h2>Explore</h2>
          <p>Every crevice without limitations</p>
        </div>
      </div>
    </div>


  </div>
</div>
 -->
<div class="logos-container text-center">
  <div class="container">
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://www.car-brand-names.com/wp-content/uploads/2015/04/BMW-symbol.jpg">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="https://3.bp.blogspot.com/_n_W3UtkijMQ/TJSWxOK9vUI/AAAAAAAAAJs/5JVu9ROZVCk/s1600/Honda.png">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://images.all-free-download.com/images/graphiclarge/harleydavidson_logo_29212.jpg">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://freevectorlogo.net/wp-content/uploads/2013/05/suzuki-eps-vector-logo-200x200.png">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/022014/triumph_motorcycles_2013.jpg?itok=If4-Whsc">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://www.logodesignblog.net/logos/ktmlogo-logo.jpg">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://www.asphaltandrubber.com/wp-content/uploads/2010/12/norton_logo.png">
    </div>

    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://www.freelogovectors.net/wp-content/uploads/2012/05/aprilia-logo.jpg">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="https://amsducati.com/media/wysiwyg/brands/moto-guzzi-logo.png">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://brand.polaris.com/wp-content/uploads/2015/11/Polaris_Victory_logos_Primary_1c-Black_01_696x375.png">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="http://eshop-stickers.com/sites/default/files/imagecache/node_image/yamaha_logo_5a.png">
    </div>
    <div class="col-xs-4 col-md-2 logos-margin logos">
      <img src="https://upload.wikimedia.org/wikipedia/commons/6/66/Ducati_red_logo.PNG">
    </div>
  </div>
</div>




<!-- <div class="wrapper text-center">

  <div class="card-title">
  <h2>LASTEST BIKES LISTED</h2>
  </div>
  <div class="container">

    <div class="row">
      <% @bikes.each do |bike| %>
      <div class="card-padding col-sm-6 col-md-4">


        <div class="card" style="background-image: url('<%= image_url bike.bike_image %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

          <div class="card-category"><%= bike.make %></div>
          <div class="card-description">
            <h2><%= bike.model %></h2>
          </div>

        </div>

      </div>
      <% end %>
    </div>
  </div>
</div> -->



<%= render 'shared/footer' %>