config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :locations, only: [:index, :show, :new] do
    resources :bikes do
       resources :bookings
       resources :reviews, only: [:new, :create]
    end
  end

  resources :users, only: [:show] do
    resource :profile, only: [:show, :edit, :update]
  end

  get "search", to: "pages#search"
  root "pages#welcome"

end

app/models/bike.rb
class Bike < ActiveRecord::Base

  mount_uploader :bike_image, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :location
  belongs_to :user

  has_many :bookings
  has_many :reviews, :through => :bookings
  has_many :users,   :through => :bookings

  scope :latest, -> { order(created_at: :desc).limit(5) }

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  before_action :find_bike, only: [:show, :edit, :update, :destroy]

    def index
      @bikes = Bike.all
    end

    def show
      @bike = Bike.find(params[:id])
      @bikes = Bike.all
      @reviews = Review.all
      # @review = Review.find(params[:review_id])
      @location = Location.find(params[:location_id])
      @booking = @bike.bookings.new
      @alert_message = "You are viewing #{@bike.make}"
      @bikes = @bikes.select{ |b| b.latitude }
      @markers = Gmaps4rails.build_markers(@bike) do |bike, marker|
        marker.lat bike.latitude
        marker.lng bike.longitude
      end
    end



    def new
      @bike = location.bikes.new
    end

    def create
      @bike = location.bikes.build(bike_params)
      @bike.user = current_user
      if @bike.save
        redirect_to location_bike_path(location, @bike)
      else
        render :new
      end
    end

    def edit
    end

    def update
      # @bike = Bike.update(bike_params)
    end

    def destroy
      @bike.destroy
    end

    def search
      @bikes = Bike.where(location_id: params[:location_id])

      start_date = params[:start_date].to_date
      end_date = params[:end_date].to_date


      @bikes.each do |bike|
        bike.bookings.each do |booking|
          booking_start = booking.start_date
          booking_end = booking.end_date
          if (start_date > booking_start && start_date < booking_end) || (end_date > booking_start && end_date < booking_end) || (start_date < booking_start && end_date > booking_start)
            @bikes = @bikes.reject{|b| b.id == bike.id }
            break
          end
        end
      end
    @bikes
    end

  private

    def bike_params
      params.require(:bike).permit(:make, :model, :engine, :year, :bike_type, :rate_daily, :address, :bike_image)
    end

    def location
      @location = Location.find(params[:location_id])
    end

    def find_bike
      @bike = Bike.find(params[:id])
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/edit.html.erb
<h1>Bikes#edit</h1>
<p>Find me in app/views/bikes/edit.html.erb</p>

app/views/bikes/index.html.erb
<h1>Bikes#index</h1>


<% @bikes.each do |bike|%>
  <h1> <%= bike.bike_image %> </h1>
  <h3> <%= link_to bike.make, location_bikes_path(bike) %> </h3>
  <p>  <%= bike.model %> </p>
  <p>  <%= bike.bike_type %> </p>
  <p>  <%= bike.engine %> </p>
  <p>  <%= bike.year %> </p>
<% end %>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>

    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/bikes/new.html.erb
<div class="form-left" style="background-image:  url('http://www.teknohabernet.com/wp-content/uploads/2015/12/Ducati-Duvar-Kagidi-1.png');">
  <div class="banner-content">
    <br>
    <br>
    <br>
    <h1>List Your Bike</h1>

     <div class="wrapper-form">


      <%= simple_form_for [@location, @bike] do |f| %>
        <%= f.input :make %>
        <%= f.input :model %>
        <%= f.input :engine %>
        <%= f.input :year %>
        <%= f.input :bike_type %>
        <%= f.input :rate_daily %>
        <%= f.input :address %>
        <%= f.input :bike_image %>
        <%= f.button :submit %>
      <% end %>





       <!--  <input type="date" class="form-control input-md" placeholder="check in">
        <input type="date" class="form-control input-md" placeholder="check out">
        <select class="form-control input-md" placeholder="Type">
          <option value="1">Type</option>
          <option value="2">Scooter</option>
          <option value="3">Motorcycle</option>
          <option value="4">Moped</option>
        </select> -->
        <!-- <input type="submit" class="btn btn-info btn-md" value="Search"> -->


      <br><br>

    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="container">
<!-- <div class="media"> -->

<div class="row">

      <div class="media-bodies">
      <div class="col-xs-12 col-sm-6">

        <div class="media-section">
          <h2><%= @bike.make%></h2><p><%= @bike.model%></p>
          <%= cl_image_tag @bike.bike_image %>
        </div>


        <div class="media-section">
          <p>Make: <%= @bike.make%></p>
          <p>Model: <%= @bike.model%></p>
          <p>Engine: <%= @bike.engine%></p>
          <p>Year: <%= @bike.year%></p>
          <p>Type: <%= @bike.bike_type%></p>
          <p>Daily rate: $ <%= @bike.rate_daily%>.00</p>
          <p>Location: <%= @location.city%></p>
          <p>Address: <%= @bike.address%></p>
        </div>
      </div>
      </div>



      <div class="media-side">
      <div class="col-xs-12 col-sm-6">
        <div class="media-section">


          <div id="map" style="width: 100%; height: 500px;"></div>

          <br><br>


          <%= render 'shared/booking' %>

          <br><br><br><br><br>

          <p><%= link_to "Add a review", new_location_bike_review_path(@location, @bike)%>
          </p>

          <div class="media-section">
            <h4>Reviews: </h4>
            <% @bike.bookings.each do |booking| %>
              <% booking.reviews.each do |r| %>
                <p> Review: <%= r.description %> </p>
                <p> Rating: (1-5): <%= r.rating %> </p>
              <% end %>
            <% end %>
          </div>

          <h4>Share - 382 upvotes</h4>
          <div class="share-links">
            <a href="#" class="share-link bg-facebook">
              <i class="fa fa-facebook"></i>
            </a>
            <a href="#" class="share-link bg-twitter">
              <i class="fa fa-twitter"></i>
            </a>
            <a href="#" class="share-link bg-email">
              <i class="fa fa-envelope-o"></i>
            </a>
            <a href="#" class="share-link bg-text">
              <i class="fa fa-mobile"></i>
            </a>
          </div>


        </div>
      </div>
      </div>

  </div>
<!-- </div> -->
</div>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>