config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :locations, only: [:index, :show, :new] do
    resources :bikes do
       resources :bookings
       resources :reviews, only: [:new, :create]
    end
  end

  resources :users, only: [:show] do
    resource :profile, only: [:show, :edit, :update]
  end

  get "search", to: "pages#search"
  root "pages#welcome"

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :bikes
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
    if params[:location_id]
      @location = Location.find(params[:location_id])
      redirect_to location_path(@location)
    end
  end

  def show
    @location = Location.find(params[:id])
    @bikes = Bike.all
      # @review = Review.find(params[:review_id])
    @bikes = @bikes.select{ |b| b.latitude }
    @markers = Gmaps4rails.build_markers(@bikes) do |bike, marker|
      marker.lat bike.latitude
      marker.lng bike.longitude
    end

  end



  # def new
  #   @bike = Bike.find(params[:bike_id])
  #   @location = @bike.locations.new
  # end

  # def create
  #   @bike = Bike.find(params[:bike_id])
  #   @location = @bike.locations.build(location_params)
  #   if @location.save!
  #     redirect_to locations_path
  #   else
  #     redirect_to root_path
  #   end
  # end

  # private

  # def location_params
  #   params.require(:location).permit(:country, :city)
  # end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>


<%= simple_form_for [@bike, @location] do |f| %>
  <%= f.input :country %>
  <%= f.input :city %>
  <%= f.button :submit %>
<% end %>

app/views/locations/show.html.erb
<!-- <h1 class='text-center'> <%= @location.city%></h1>
<br>
<br>
 -->

<!-- <div class="text-center">
  <%= link_to t(".top_call_to_action", default: "List your bike"), new_location_bike_path(@location), class: "navbar-wagon-item btn-treehouse" %>
</div>

 -->
<div class="banner text-center" style="background-image: linear-gradient(23deg, rgba(0,0,0,0) -158%, rgba(0,4,13,9) 143%), url('http://www.wallcoo.net/nature/Window7_Europe_Wallpapers_1920x1200/wallpapers/1920x1200/Britain,%20River%20Thames%20and%20Tower%20Bridge%20at%20Dusk,%20London,%20England.jpg');">
  <div class="banner-content">
    <h1 class='text-center'> <%= @location.city%></h1>
    <br><br>
    <div class="text-center">
      <%= link_to t(".top_call_to_action", default: "List your bike"), new_location_bike_path(@location), class: "navbar-wagon-item btn-treehouse" %>
    </div>
  </div>
</div>

<div class="banner-wrapper">
  <div class="banner-content-center text-center">

    <h1>Available Bikes In <%= @location.city %></h1>
    <br>

  </div>

</div>

<div class= "container-bottom-padding">
  <div class="container-local">
    <div class="row">

      <div class="bike-cards">
      <div class="col-xs-12 col-sm-6 scrollable">
        <% @location.bikes.each do |bike| %>
        <div class="col-xs-12 card-padding">

          <%= link_to location_bike_path(@location, bike) do %>
          <div class="card" style="background-image: url('<%= image_url bike.bike_image %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

            <div class="card-category"><h3><%= bike.make %></h3></div>
            <div class="card-description">
              <p><%= bike.model %></p>
            </div>

          </div>
          <% end %>
        </div>
        <% end %>
      </div>
      </div>


      <div class="bike-maps">
      <div class="col-xs-12 col-sm-6 bike-maps-padding">
        <div id="map" style="width: 100%; height: 600px; zoom: 1"></div>
        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).on('ready', function() {
              handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @markers.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
              });
            })
          <% end %>
        <% end %>
      </div>
      </div>

    </div>
  </div>
</div>